# @name authorization
POST https://cloud.squidex.io/identity-server/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=5e33e480d6c2080001c91a7d&client_secret=fazsugjn9wekkbfrb6fs89rn41jyt5zhohtnyv7ovvkx&scope=squidex-api

@accessToken = {{authorization.response.body.$.access_token}}

###
GET https://cloud.squidex.io/api/content/cleverdev/posts/
Authorization: Bearer {{accessToken}}
X-Flatten: true

###
GET https://cloud.squidex.io/api/content/cleverdev/pages/
Authorization: Bearer {{accessToken}}
X-Flatten: true


###
GET https://cloud.squidex.io/api/content/cleverdev/posts/844c3ca4-47a0-437d-910c-eff1778cca5f
Authorization: Bearer {{accessToken}}
X-Flatten: true

###
HEAD https://cloud.squidex.io/api/assets/cleverdev/5219ba09-30b8-4b2f-a0d8-c6a92d50804d/about.jpg?version=0